# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    # This is a basic workflow to help you get started with Actions
    - name: First interaction
      uses: actions/first-interaction@v1.1.0
      with:
        # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        # Comment to post on an individual's first issue
        issue-message: Thankyou for your contribution 🎉. Kindly write a breif description here about your pull request here. It will help us to look into it and know better. 
        # Comment to post on an individual's first pull request
        pr-message: Thanks for your contribution ✨
    - name: Send Telegram notification.
      uses: yanzay/notify-telegram@v0.1.0
      if: always()
      with:
        chat: ${{ secrets.CHAT }} # user id or channel name secret
        token: ${{ secrets.TOKEN }} # token secret
        status: ${{ job.status }} # do not modify this line

